name: Deploy to github 

on:
    push:
        branches: [ main ]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                    node-version: '24'

            - name: Install dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                name: 'github-pages'
                path: dist
            
            - name: Deploy to Github Pages
              uses: actions/deploy-pages@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                artifact_name: 'github-pages'
            